name = "badminton"
main = "src/worker.js"
compatibility_date = "2026-07-09"

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.txt"]
fallthrough = true

[[d1_databases]]
binding = "DB"
database_name = "Badminton"
database_id = "9bcf9305-121d-423a-a87a-d225aa2bf5cc"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "badminton-photos"
