name = "badminton-level"
main = "src/worker.js"
compatibility_date = "2026-07-09"

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.txt"]
fallthrough = true

[[d1_databases]]
binding = "DB"
database_name = "Badminton-level"
database_id = "5715c3ab-3575-473b-ad5e-601d78eaaee1"
migrations_dir = "migrations"
