CREATE TABLE IF NOT EXISTS players (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL DEFAULT '',
  gender TEXT NOT NULL DEFAULT '男',
  level TEXT NOT NULL DEFAULT '不详',
  booking_time TEXT NOT NULL DEFAULT '19:00~22:00',
  affiliation TEXT NOT NULL DEFAULT '球友',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS level_guides (
  level TEXT PRIMARY KEY,
  description TEXT NOT NULL DEFAULT '',
  sort_order REAL NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT ''
);
